name: cc-xp-kit Test

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]

jobs:
  test-install:
    name: Test cc-xp Installation
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        install-type: [user, project]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup test environment
      run: |
        # テスト用のディレクトリを作成
        if [ "${{ matrix.install-type }}" = "project" ]; then
          mkdir -p test-project
          cd test-project
        fi
    
    - name: Test cc-xp installation
      run: |
        # インストールタイプに応じてテスト（非対話モード）
        if [ "${{ matrix.install-type }}" = "user" ]; then
          bash ${{ github.workspace }}/install.sh --user
        else
          cd test-project
          bash ${{ github.workspace }}/install.sh --project
        fi
    
    - name: Verify cc-xp installation
      run: |
        # 9つのxpファイルの確認
        XP_FILES=("discovery.md" "design.md" "scaffold.md" "tdd.md" "cicd.md" "preview.md" "review.md" "retro.md" "doc.md")
        
        if [ "${{ matrix.install-type }}" = "user" ]; then
          for file in "${XP_FILES[@]}"; do
            test -f "$HOME/.claude/commands/xp/$file"
            echo "✅ $file installed"
          done
        else
          cd test-project
          for file in "${XP_FILES[@]}"; do
            test -f ".claude/commands/xp/$file"
            echo "✅ $file installed"
          done
        fi
    
    - name: Verify xp content
      run: |
        # ファイル内容の基本確認
        XP_FILES=("discovery.md" "design.md" "scaffold.md" "tdd.md" "cicd.md" "preview.md" "review.md" "retro.md" "doc.md")
        
        if [ "${{ matrix.install-type }}" = "user" ]; then
          commands_dir="$HOME/.claude/commands/xp"
        else
          cd test-project
          commands_dir=".claude/commands/xp"
        fi
        
        # 各ファイルに適切なキーワードが含まれているか確認
        grep -q "Intent Model" "$commands_dir/discovery.md"
        grep -q "C4" "$commands_dir/design.md"
        grep -q "scaffold" "$commands_dir/scaffold.md"
        grep -q "TDD" "$commands_dir/tdd.md"
        grep -q "CI/CD" "$commands_dir/cicd.md"
        echo "✅ All xp files have correct content"

  test-suite:
    name: Run Test Suite
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run cc-xp test suite
      run: |
        bash tests/run-tests.sh

  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        check_together: 'yes'
        severity: 'error'

