name: cc-xp-kit Test

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]

jobs:
  test-install:
    name: Test cc-xp Installation
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        install-type: [user, project]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup test environment
      run: |
        # テスト用のディレクトリを作成
        if [ "${{ matrix.install-type }}" = "project" ]; then
          mkdir -p test-project
          cd test-project
        fi
    
    - name: Test cc-xp installation
      run: |
        # インストールタイプに応じてテスト（非対話モード）
        if [ "${{ matrix.install-type }}" = "user" ]; then
          bash ${{ github.workspace }}/install.sh --user
        else
          cd test-project
          bash ${{ github.workspace }}/install.sh --project
        fi
    
    - name: Verify cc-xp installation
      run: |
        # 5つのcc-xpファイルの確認
        CC_XP_FILES=("plan.md" "story.md" "develop.md" "review.md" "retro.md")
        
        if [ "${{ matrix.install-type }}" = "user" ]; then
          for file in "${CC_XP_FILES[@]}"; do
            test -f "$HOME/.claude/commands/$file"
            echo "✅ $file installed"
          done
        else
          cd test-project
          for file in "${CC_XP_FILES[@]}"; do
            test -f ".claude/commands/$file"
            echo "✅ $file installed"
          done
        fi
    
    - name: Verify cc-xp content
      run: |
        # ファイル内容の基本確認
        CC_XP_FILES=("plan.md" "story.md" "develop.md" "review.md" "retro.md")
        
        if [ "${{ matrix.install-type }}" = "user" ]; then
          commands_dir="$HOME/.claude/commands"
        else
          cd test-project
          commands_dir=".claude/commands"
        fi
        
        # 各ファイルにXPキーワードが含まれているか確認
        grep -q "XP plan" "$commands_dir/plan.md"
        grep -q "XP story" "$commands_dir/story.md"
        grep -q "XP develop" "$commands_dir/develop.md"
        grep -q "XP review" "$commands_dir/review.md"
        grep -q "XP retro" "$commands_dir/retro.md"
        echo "✅ All cc-xp files have correct content"

  test-suite:
    name: Run Test Suite
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run cc-xp test suite
      run: |
        bash tests/run-tests.sh

  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        check_together: 'yes'
        severity: 'error'

